### ISSUE TITLE
Conflicting file prevents installation of kconfig-git

### ISSUE THREAD

**Issue by JensDA** [chaotic-aur/pkgbuild-ki18n-git#2]
```
error: failed to commit transaction (conflicting files)
kconfig-git: /usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in filesystem (owned by ki18n-git)
```

**Comment by IslandC0der** [comment]
Very strange, I thought I had already fixed this issue.
~Could you try running `pacman -Fyy` and `pacman -Syyu` before attempting to install it? I think your pacman database is outdated.~

EDIT: If you compiled it yourself, make sure you are using the latest version of `extra-cmake-modules-git` when doing so. I recommend rebuilding both `kconfig-git` and `ki18n-git` (and any other affected packages), and the problem should go away.

EDIT2: Actually, the AUR maintainer hasn't accepted my patch :(
So, if you also compiled `extra-cmake-modules-git` yourself, please do so using [this PKGBUILD and patch](https://github.com/chaotic-aur/pkgbuild-extra-cmake-modules-git), for the time being.

**Comment by JensDA** [comment]
Fixed with patched extra-cmake-modules-git.
